- alias: Turn on lights at dusk
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: -4
  action:
    service: light.turn_on
    entity_id: 
      - light.ge_unknown_type_4944_id_3039_level   # Porch
      - light.ge_45606_2_way_dimmer_switch_level   # Nook
      - light.ge_unknown_type_4944_id_3039_level_3 # Deco
    data:
      brightness: 255

- alias: Turn off lights at 22:00
  trigger:
    platform: time
    at: '22:00:00'
  action:
    service: light.turn_off
    entity_id: 
      - light.ge_unknown_type_4944_id_3039_level   # Porch
      - light.ge_45606_2_way_dimmer_switch_level   # Nook
      - light.ge_unknown_type_4944_id_3039_level_3 # Deco

- alias: Alarm disarmed
  trigger:
    platform: state
    entity_id: alarm_control_panel.alarm_panel
    to: 'disarmed'
  action:
    - service: notify.pushover_notifier
      data:
        message: "Alarm disarmed"

- alias: Alarm armed home
  trigger:
    platform: state
    entity_id: alarm_control_panel.alarm_panel
    to: 'armed_home'
  action:
    - service: notify.pushover_notifier
      data:
        message: "Alarm armed HOME"
    - service: light.turn_off
      entity_id: 
        - light.ge_unknown_type_4944_id_3039_level   # Porch
        - light.ge_45606_2_way_dimmer_switch_level   # Nook
        - light.ge_unknown_type_4944_id_3039_level_3 # Deco

- alias: Alarm armed AWAY
  trigger:
    platform: state
    entity_id: alarm_control_panel.alarm_panel
    to: 'armed_away'
  action:
    service: notify.pushover_notifier
    data:
      message: "Alarm armed AWAY"

- alias: Alarm TRIGGERED
  trigger:
    platform: state
    entity_id: alarm_control_panel.alarm_panel
    to: 'triggered'
  action:
    - service: notify.pushover_notifier
      data:
        message: "Alarm TRIGGERED"
    - service: light.turn_on
      entity_id: 
        - light.ge_unknown_type_4944_id_3039_level   # Porch
        - light.ge_45606_2_way_dimmer_switch_level   # Nook
        - light.ge_unknown_type_4944_id_3039_level_3 # Deco

- alias: Turn on downstairs on motion
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.ge_unknown_type_4944_id_3039_level_3
        state: 'off'
      - condition: sun
        after: sunset
  action:
    - service: light.turn_on
      entity_id: 
        - light.ge_45606_2_way_dimmer_switch_level   # Nook
        - light.ge_unknown_type_4944_id_3039_level_3 # Deco
      data:
        brightness: 127
    - service: timer.start
      data:
        entity_id: timer.downstairs_lights

- alias: Turn off downstairs on timer
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.downstairs_lights
  action:
    service: light.turn_off
    data:
      entity_id:
        - light.ge_45606_2_way_dimmer_switch_level   # Nook
        - light.ge_unknown_type_4944_id_3039_level_3 # Deco

