homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1821
  unit_system: metric
  time_zone: America/Denver
  customize: !include customize.yaml

# Enables the frontend
frontend:

lovelace:
  mode: yaml

# Enables configuration UI
config:

http: !include http.yaml

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  - platform: nut
    resources:
      - ups.load
      - ups.realpower.nominal
      - input.voltage
      - battery.runtime

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

duckdns: !include duckdns.yaml

ecobee:
  api_key: !secret ecobee_api_key

rachio:
  api_key: !secret rachio_api_key

zwave:
  usb_path: /dev/ttyACM0

notify:
  - name: pushover_notifier
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

alarmdecoder: !include alarm.yaml

scene: !include scenes.yaml

light:
  - platform: hyperion
    host: 192.168.1.4

timer:
  downstairs_lights:
    duration: '00:05:00'

recorder:
  exclude:
    domains:
      - alarm_control_panel
      - weather
    entities:
      - sun.sun
      - sensor.alarm_panel_display

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
    aliases:
        abc123def456: 'Living Room'
        9183abas000: 'Bed Room'

system_health:

vacuum:
  - platform: roomba
    host: 192.168.1.100
    username: !secret roomba_username
    password: !secret roomba_password
