version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:2021.11
    volumes:
      - /home/pi/homeassistant/config:/config
    environment:
      - TZ=America/Denver
    devices:
      - /dev/zwave:/dev/zwave
      - /dev/zigbee:/dev/zigbee
    restart: always
    ports:
      - 8123:8123
    links:
      - zjs:zjs
  zjs:
    container_name: zjs
    image: kpine/zwave-js-server:1.13.0-8.8.3
    restart: unless-stopped
    environment:
      S2_ACCESS_CONTROL_KEY: ${S2_ACCESS_CONTROL_KEY}
      S2_AUTHENTICATED_KEY: ${S2_AUTHENTICATED_KEY}
      S2_UNAUTHENTICATED_KEY: ${S2_UNAUTHENTICATED_KEY}
      S0_LEGACY_KEY: ${S0_LEGACY_KEY}
    devices:
      - '/dev/zwave:/dev/zwave'
    volumes:
      - ./cache:/cache
    ports:
      - '3000:3000'      
