- id: turn_lights_on_at_dusk
  alias: Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:00
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id:
      - light.2_way_dimmer_switch
      - light.in_wall_1000w_incandescent_smart_dimmer
      - light.kitchen
  - service: cover.set_cover_position
    data:
      position: 0
    target:
      device_id:
      - 8c94e2ef8d558b3f458ade46079e2b6d
      - 8e2d03126285962c5cf5f5e225fd1ed5
    enabled: false
  - service: cover.set_cover_position
    data:
      position: 16
    target:
      device_id: 25d16fcb4cc550571e280dbae4c88339
    enabled: false
  - service: switch.turn_on
    data: {}
    target:
      device_id: 856f95f5fae4f0101558eefbdc0be8a9
- id: turn_lights_off_at_2200
  alias: Turn off lights at 22:00
  trigger:
  - platform: time
    at: '22:00:00'
  action:
  - type: turn_off
    device_id: cf0dd4b30cf0fef6b4aa899339adb538
    entity_id: light.2_way_dimmer_switch
    domain: light
  - service: cover.set_cover_position
    data:
      position: 0
    target:
      entity_id: cover.tv_area
- id: lock_door_at_2200
  alias: Lock door at 22:00
  trigger:
  - platform: time
    at: '22:00:00'
  action:
  - service: lock.lock
    entity_id:
    - lock.touchscreen_deadbolt_z_wave_plus
- id: turn_off_porch_lights_at_0000
  alias: Turn off porch lights at 00:00
  trigger:
  - at: 00:00:00
    platform: time
  action:
  - entity_id:
    - light.in_wall_1000w_incandescent_smart_dimmer
    service: light.turn_off
- id: bedtime
  alias: Bedtime
  trigger:
  - event_data:
      actionName: Bedtime
    event_type: ios.action_fired
    platform: event
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.2_way_dimmer_switch
      - light.deco
      - light.kitchen
      - light.master_bedroom
      - light.mudroom
      - light.wled_2
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.z_wave_plus_s2_on_off_switch_2
      - switch.z_wave_plus_s2_on_off_switch_3
  - service: cover.set_cover_position
    data:
      position: 0
    target:
      entity_id: cover.bay_window
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.christmas_tree_switch
  initial_state: true
- id: notification_front_door_unlocked
  alias: Front door unlocked
  trigger:
  - platform: state
    to: unlocked
    entity_id: lock.touchscreen_deadbolt_z_wave_plus
  action: []
- id: notification_front_door_locked
  alias: Front door locked
  trigger:
  - platform: state
    to: locked
    entity_id: lock.touchscreen_deadbolt_z_wave_plus
  action: []
- id: alarm_quick_arm
  alias: Quick alarm arm
  trigger:
  - device_id: 1510fd60e9824f50aad4b0cbc15fc2f3
    domain: zha
    platform: device
    subtype: remote_button_double_press
    type: remote_button_double_press
  condition: []
  action:
  - data:
      code: 1248
    entity_id: alarm_control_panel.alarm_panel
    service: alarm_control_panel.alarm_arm_home
- id: home_theater_full_brightness
  alias: Home theater full brightness
  trigger:
  - device_id: 31f0e2ce39fbf8bafae12aa0a47fe958
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.basement_stairs
  - service: light.turn_on
    data:
      transition: 5
      brightness_pct: 100
    target:
      entity_id: light.in_wall_1000w_incandescent_smart_dimmer_5
- id: '1595543370498'
  alias: Double door Toggle
  description: ''
  trigger:
  - event_data:
      actionName: Double Door
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.double_garage_door
- id: '1595627402225'
  alias: Single Door toggle
  description: ''
  trigger:
  - event_data:
      actionName: Single Door
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.single_garage_door
- id: '1639629896297'
  alias: Living Room TV Time
  description: ''
  trigger:
  - device_id: 4f14e55e1ec5d5b73e85b33b9660270d
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - type: turn_off
    device_id: 7ccede0eb6b66c75d77dc182d0e848b4
    entity_id: light.in_wall_1000w_incandescent_smart_dimmer_2
    domain: light
  - type: turn_off
    device_id: 0aac16db9fa2041cac3cfbbcbdb82205
    entity_id: switch.z_wave_plus_s2_on_off_switch_3
    domain: switch
  - type: turn_on
    device_id: cf0dd4b30cf0fef6b4aa899339adb538
    entity_id: light.2_way_dimmer_switch
    domain: light
    brightness_pct: 50
  mode: single
- id: home_theater_on
  alias: Home Theater ON
  description: ''
  trigger:
  - device_id: sensor.samjin_button_power
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - type: turn_on
    entity_id: switch.z_wave_plus_s2_on_off_switch_2
    domain: light
    brightness_pct: 50
  mode: single
- id: '1643680657952'
  alias: Living room fan lights on
  description: ''
  trigger:
  - device_id: 4f14e55e1ec5d5b73e85b33b9660270d
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - type: turn_on
    device_id: 0aac16db9fa2041cac3cfbbcbdb82205
    entity_id: switch.z_wave_plus_s2_on_off_switch_3
    domain: switch
  mode: single
- id: '1646944298379'
  alias: Home Theater Lights off
  description: ''
  trigger:
  - device_id: 31f0e2ce39fbf8bafae12aa0a47fe958
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.basement_stairs
  - service: light.turn_off
    data:
      transition: 2
    target:
      entity_id: light.in_wall_1000w_incandescent_smart_dimmer_5
  mode: single
- id: '1646944375772'
  alias: Home Theater Dim
  description: ''
  trigger:
  - device_id: 31f0e2ce39fbf8bafae12aa0a47fe958
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: remote_button_long_press
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 40
      transition: 2
    target:
      entity_id: light.in_wall_1000w_incandescent_smart_dimmer_5
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.basement_stairs
  mode: single
- id: '1670809105272'
  alias: Kitchen Lights Mirror State
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.kitchen
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: light.kitchen
        state: 'off'
      sequence:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.nano_dimmer
    - conditions:
      - condition: state
        entity_id: light.kitchen
        state: 'on'
      sequence:
      - service: light.turn_on
        data:
          brightness_pct: 100
        target:
          entity_id: light.nano_dimmer
  mode: single
- id: '1671052940118'
  alias: Sunrise
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - service: cover.set_cover_position
    data:
      position: 100
    target:
      entity_id: cover.bay_window
  mode: single
- id: '1671471776765'
  alias: Toggle Zoey's office lights
  description: ''
  trigger:
  - device_id: be1f8ee8f0a91c959971b8e21f16d063
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: light.toggle
    data:
      brightness_pct: 100
      rgb_color:
      - 255
      - 255
      - 255
    target:
      device_id: 364f7d1aaaf7fa9b77522724dc4021ae
  mode: single
- id: '1671477641173'
  alias: Toggle Pierre's office lights on
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: aecfe1bf49fe7c3da84f6c8c31b15f97
    entity_id: switch.z_wave_plus_s2_on_off_switch
    domain: switch
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
    target:
      entity_id: light.wled
  mode: single
- id: '1671477723524'
  alias: Turn off Pierre's office lights
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: aecfe1bf49fe7c3da84f6c8c31b15f97
    entity_id: switch.z_wave_plus_s2_on_off_switch
    domain: switch
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.wled
  mode: single
- id: '1672076573259'
  alias: Turn on Zoey’s desk, pink
  description: ''
  trigger:
  - device_id: be1f8ee8f0a91c959971b8e21f16d063
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_step_pct: 100
      rgb_color:
      - 193
      - 84
      - 193
    target:
      device_id: 364f7d1aaaf7fa9b77522724dc4021ae
  mode: single
- id: '1682947446870'
  alias: Close TV area blinds around sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:20:00
  condition: []
  action:
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.tv_area
      area_id: reading_room
  mode: single
- id: '1682947531535'
  alias: Open TV area blinds on sunset
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - service: cover.open_cover
    data: {}
    target:
      entity_id: cover.tv_area
  mode: single
- id: '1695301407278'
  alias: Kitchen lights at sunrise
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_on
    data: {}
    target:
      area_id: kitchen
  mode: single
- id: '1699248425400'
  alias: Morning bedroom light
  description: Turns on master bedroom light at 6:30 on weekdays
  trigger:
  - platform: time
    at: 06:30:00
  condition:
  - condition: time
    weekday:
    - fri
    - thu
    - wed
    - tue
    - mon
  action:
  - service: light.turn_on
    data:
      transition: 60
      brightness_pct: 100
    target:
      area_id: bedroom
  mode: single
- id: '1700264235971'
  alias: Turn on Pierre's office at sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_on
    data:
      rgb_color:
      - 255
      - 255
      - 255
      brightness_pct: 100
    target:
      area_id: pierre_s_office
  mode: single
- id: '1700535569011'
  alias: zoey's fairy lights
  description: ''
  trigger:
  - device_id: 4f14e55e1ec5d5b73e85b33b9660270d
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: switch.toggle
    data: {}
    target:
      device_id: ecffdf114d3f9aa27472551d04008a0e
- id: elodie_office_light
  alias: elodie's office light
  trigger:
  - event_data:
      actionName: Office Light
    event_type: ios.action_fired
    platform: event
  action:
  - service: switch.toggle
    data: {}
    target:
      area_id: elodie_s_office
  mode: single
