- id: home_theater_lights_off
  alias: Home theater light turn OFF
  trigger:
  - device_id: 7d53030f10654b99b37b7ebb1ec2e8f0
    domain: zha
    platform: device
    subtype: remote_button_short_press
    type: remote_button_short_press
  condition:
  - condition: device
    device_id: 064b2228cf41464db56c2bcbec741f02
    domain: light
    entity_id: light.jasco_products_14299_in_wall_1000w_smart_dimmer_level_3
    type: is_on
  action:
  - entity_id:
    - light.jasco_products_14299_in_wall_1000w_smart_dimmer_level_3
    - switch.basement_stairs_switch
    service: light.turn_off
  - device_id: 7db41220f7794b269be54b2054f76e36
    domain: switch
    entity_id: switch.basement_stairs_switch
    type: turn_off
- id: turn_lights_on_at_dusk
  alias: Turn on lights at dusk
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: -1
  action:
    service: light.turn_on
    entity_id:
    - light.in_wall_1000w_incandescent_smart_dimmer
    - light.jasco_products_45606_2_way_dimmer_switch_level
    - light.jasco_products_14299_in_wall_1000w_smart_dimmer_level
    data:
      brightness: 255
- id: turn_lights_off_at_2200
  alias: Turn off lights at 22:00
  trigger:
    platform: time
    at: '22:00:00'
  action:
    service: light.turn_off
    entity_id:
    - light.jasco_products_45606_2_way_dimmer_switch_level
    - light.jasco_products_14299_in_wall_1000w_smart_dimmer_level
- id: lock_door_at_2200
  alias: Lock door at 22:00
  trigger:
  - platform: time
    at: '22:00:00'
  action:
  - service: lock.lock
    entity_id:
    - lock.touchscreen_deadbolt_z_wave_plus
- id: turn_off_porch_lights_at_0000
  alias: Turn off porch lights at 00:00
  trigger:
  - at: 00:00:00
    platform: time
  action:
  - entity_id:
    - light.in_wall_1000w_incandescent_smart_dimmer
    service: light.turn_off
- id: notification_alarm_disarmed
  alias: Alarm disarmed
  trigger:
    platform: state
    entity_id: alarm_control_panel.alarm_panel
    to: disarmed
  action:
  - service: notify.pushover_notifier
    data:
      message: Alarm disarmed
- id: notification_alarm_armed_home
  alias: Alarm armed home
  trigger:
    platform: state
    entity_id: alarm_control_panel.alarm_panel
    to: armed_home
  action:
  - service: notify.pushover_notifier
    data:
      message: Alarm armed HOME
- id: notification_alarm_armed_away
  alias: Alarm armed AWAY
  trigger:
    platform: state
    entity_id: alarm_control_panel.alarm_panel
    to: armed_away
  action:
    service: notify.pushover_notifier
    data:
      message: Alarm armed AWAY
- id: notification_alarm_triggered
  alias: Alarm TRIGGERED
  trigger:
    platform: state
    entity_id: alarm_control_panel.alarm_panel
    to: triggered
  action:
  - service: notify.pushover_notifier
    data:
      message: Alarm TRIGGERED
  - service: light.turn_on
    entity_id:
    - light.jasco_products_14299_in_wall_1000w_smart_dimmer_level_4
    - light.jasco_products_45606_2_way_dimmer_switch_level
    - light.jasco_products_14299_in_wall_1000w_smart_dimmer_level
- id: turn_on_downstairs_on_motion
  alias: Turn on downstairs on motion
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.jasco_products_14299_in_wall_1000w_smart_dimmer_level
      state: 'off'
    - condition: sun
      after: sunset
  action:
  - service: light.turn_on
    entity_id:
    - light.jasco_products_45606_2_way_dimmer_switch_level
    - light.jasco_products_14299_in_wall_1000w_smart_dimmer_level
    data:
      brightness: 127
  - service: light.turn_on
    data:
      entity_id: light.bookshelf_left
      rgb_color:
      - 255
      - 0
      - 0
      brightness: 200
      transition: 2
      effect: Solid
  - service: timer.start
    data:
      entity_id: timer.downstairs_lights
- id: turn_on_garage_for_5_min
  alias: Turn on Garage lights for 5 mins
  trigger:
  - entity_id: binary_sensor.ecolink_door_window_sensor_sensor
    platform: state
    to: 'on'
  - entity_id: binary_sensor.garage_door
    platform: state
    to: 'on'
  condition:
  - after: sunset
    condition: sun
  action:
  - entity_id: switch.garage_lights
    service: switch.turn_on
  - data:
      entity_id: timer.garage_lights
    service: timer.start
- id: turn_off_garage_lights_on_timer
  alias: Turn off garage lights on timer
  trigger:
  - event_data:
      entity_id: timer.garage_lights
    event_type: timer.finished
    platform: event
  action:
  - data:
      entity_id:
      - switch.zooz_zen26_s2_on_off_wall_switch_switch_2
    entity_id: switch.garage_lights
    service: switch.turn_off
- id: turn_off_downstairs_on_timer
  alias: Turn off downstairs on timer
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.downstairs_lights
  action:
    service: light.turn_off
    data:
      entity_id:
      - light.jasco_products_45606_2_way_dimmer_switch_level
      - light.jasco_products_14299_in_wall_1000w_smart_dimmer_level
      - light.bookshelf_left
- id: bedtime
  alias: Bedtime
  trigger:
  - event_data:
      actionName: Bedtime
    event_type: ios.action_fired
    platform: event
  - device_id: 31f0e2ce39fbf8bafae12aa0a47fe958
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: remote_button_long_press
  action:
  - entity_id:
    - light.in_wall_1000w_incandescent_smart_dimmer_3
    - light.2_way_dimmer_switch
    - light.in_wall_1000w_incandescent_smart_dimmer_4
    service: light.turn_off
  initial_state: true
- id: notification_front_door_unlocked
  alias: Front door unlocked
  trigger:
  - platform: state
    to: unlocked
    entity_id: lock.touchscreen_deadbolt_z_wave_plus
  action:
  - service: notify.pushover_notifier
    data:
      message: Front door unlocked
- id: notification_front_door_locked
  alias: Front door locked
  trigger:
  - platform: state
    to: locked
    entity_id: lock.touchscreen_deadbolt_z_wave_plus
  action:
  - service: notify.pushover_notifier
    data:
      message: Front door locked
- id: toggle_master_bedroom_light
  alias: Toggle master bedroom light
  trigger:
  - device_id: 1510fd60e9824f50aad4b0cbc15fc2f3
    domain: zha
    platform: device
    subtype: remote_button_short_press
    type: remote_button_short_press
  condition: []
  action:
  - entity_id:
    - light.jasco_products_14299_in_wall_1000w_smart_dimmer_level_6
    service: light.toggle
- id: alarm_quick_arm
  alias: Quick alarm arm
  trigger:
  - device_id: 1510fd60e9824f50aad4b0cbc15fc2f3
    domain: zha
    platform: device
    subtype: remote_button_double_press
    type: remote_button_double_press
  condition: []
  action:
  - data:
      code: 1248
    entity_id: alarm_control_panel.alarm_panel
    service: alarm_control_panel.alarm_arm_home
- id: home_theater_full_brightness
  alias: Home theater full brightness
  trigger:
  - device_id: 31f0e2ce39fbf8bafae12aa0a47fe958
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - type: turn_on
    device_id: ef309bc9bc895cef8d7578589feead1a
    entity_id: switch.z_wave_plus_s2_on_off_switch_2
    domain: switch
- id: home_theater_lights_on
  alias: Home theater light turn ON
  trigger:
  - device_id: 7d53030f10654b99b37b7ebb1ec2e8f0
    domain: zha
    platform: device
    subtype: remote_button_short_press
    type: remote_button_short_press
  condition:
  - condition: device
    device_id: 064b2228cf41464db56c2bcbec741f02
    domain: light
    entity_id: light.jasco_products_14299_in_wall_1000w_smart_dimmer_level_3
    type: is_off
  action:
  - brightness_pct: 20
    device_id: 064b2228cf41464db56c2bcbec741f02
    domain: light
    entity_id: light.jasco_products_14299_in_wall_1000w_smart_dimmer_level_3
    type: turn_on
- id: '1595543370498'
  alias: Double door Toggle
  description: ''
  trigger:
  - event_data:
      actionName: Double Door
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: switch.zooz_unknown_type_a000_id_a00a_switch
    service: switch.toggle
- id: '1595627402225'
  alias: Single Door toggle
  description: ''
  trigger:
  - event_data:
      actionName: Single Door
    event_type: ios.action_fired
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: switch.zooz_unknown_type_a000_id_a00a_switch_2
    service: switch.toggle
- id: '1609728555315'
  alias: Switch Pierre's Office lights
  description: ''
  trigger:
  - device_id: be1f8ee8f0a91c959971b8e21f16d063
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - type: toggle
    device_id: 64caafb6cd9316d7fce7c377f9fbee3d
    entity_id: light.wled
    domain: light
- id: '1639629896297'
  alias: Living Room TV Time
  description: ''
  trigger:
  - device_id: 4f14e55e1ec5d5b73e85b33b9660270d
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - type: turn_off
    device_id: 7ccede0eb6b66c75d77dc182d0e848b4
    entity_id: light.in_wall_1000w_incandescent_smart_dimmer_2
    domain: light
  - type: turn_on
    device_id: cf0dd4b30cf0fef6b4aa899339adb538
    entity_id: light.2_way_dimmer_switch
    domain: light
    brightness_pct: 50
  mode: single
- id: home_theater_on
  alias: Home Theater ON
  description: ''
  trigger:
  - device_id: sensor.samjin_button_power
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - type: turn_on
    entity_id: switch.z_wave_plus_s2_on_off_switch_2
    domain: light
    brightness_pct: 50
  mode: single
