- name: Movies
  entities:
    light.jasco_products_14299_in_wall_1000w_smart_dimmer_level_5: # Kitchen
      state: false
    light.2_way_dimmer_switch_level: # kittens
      state: true
      brightness: 70
